### ISSUE TITLE
Automatic backup to Google Drive

### ISSUE THREAD

**Issue by Enissay** [KamilSucharski/My-Astral-Diary#1]
Would be a great addition as you wont need to bother about doing it manually anymore :-)

Thank you for the app btw <3

**Comment by KamilSucharski** [comment]
Hey, thanks for the intrest, @Enissay!
I added the manual backup option because not everyone wants to backup to google servers, and this gives the user an indepentent mechanism they have more control of.

But, with that said, if someone does want to auto-backup to google drive, I have already set the `android:allowBackup="true"` in the manifest file https://github.com/KamilSucharski/My-Astral-Diary/blob/master/project/src/main/AndroidManifest.xml which, according to documentation "includes files created with the SQLiteOpenHelper class." (https://developer.android.com/guide/topics/data/autobackup) - so in theory it should be already implemented. I did not personally test it, as I probably won't be using it, but since you raised an issue perhaps can you confirm that for me? The documentation says something about waiting 24 hours.

**Comment by KamilSucharski** [comment]
I just checked myself and it **does** backup to google drive (if it's enabled on device).

**Comment by Enissay** [comment]
Hmm, how did you check that ?
there's no such option in app's settings

**Comment by KamilSucharski** [comment]
1. Install app
2. Add some entries
3. Close app completely
4. In **system settings** search for "backup", there should be an option to turn on system-wide backup. Turn it on and click something like "Backup now".
5. After it's finished delete the app
6. Install app again
7. Entries should be still present
